language: go
go:
  - 1.5.1
  - tip
sudo: false
before_install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
script:
  - go vet
  - go test -v
  - go test -race
addons:
  code_climate:
    repo_token: 6b69214f0cee69de0cea3e289e823b43addbc9653eb71da6d54c6b8f6ccc1199
